openapi: 3.0.0
info:
  version: 1.0.0
  title: My API
  description: This is the API
servers:
  - url: v1
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "1212121"
        name:
          type: string
          example: John Doe
        age:
          type: number
          example: 42
      required:
        - id
        - name
        - age
  parameters:
    UserId:
      in: path
      name: id
      schema:
        type: string
        example: "1212121"
      required: true
paths:
  "/users/{id}":
    get:
      description: Get user data by its id
      summary: Get a single user
      parameters:
        - in: path
          name: id
          schema:
            type: string
            example: "1212121"
          required: true
      responses:
        "200":
          description: Object with user data.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "204":
          description: No content - successful operation
